name: Cypress CI Workflow
on: pull_request
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run Cypress tests
        run: npm test:e2e
